import React from 'react';

import LayoutShell from '../components/layouts/basic-layout';

var DashboardPage = React.createClass({
  render () {
    return (
      <LayoutShell>
        DashboardLorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean maximus nunc elit, a consectetur mauris venenatis sed. Sed condimentum risus nec libero pretium viverra non ut lectus. Etiam in dui vitae leo lacinia tincidunt. Sed interdum, elit non porta condimentum, justo tellus pharetra massa, et consectetur nibh odio quis orci. Donec ac tristique velit, a congue lorem. Nulla at aliquet metus, id aliquam arcu. Integer aliquet, neque eu vehicula condimentum, nisi augue vulputate purus, ut pretium ex ex et turpis. Cras varius sapien eu augue commodo dignissim. Vestibulum ac sapien ligula. Quisque condimentum diam nec sapien mattis ultrices in pellentesque ex. Phasellus sit amet ornare ipsum. Pellentesque ultrices tincidunt felis. Nunc consectetur pellentesque augue, sed tincidunt turpis efficitur eget.
        Duis tempor sodales tellus, eget elementum ante volutpat nec. Aliquam eget eleifend neque, at lacinia nulla. Maecenas volutpat ex et mollis tincidunt. Etiam interdum dui nec fermentum facilisis. Ut auctor nulla turpis, sed ultricies quam tempor ac. Duis et risus quis eros pretium porta. Aenean in dolor id nisi aliquet vestibulum. Vestibulum quam ipsum, semper a metus vel, consequat egestas ipsum. Sed lorem odio, dictum ut viverra sit amet, fringilla non tellus. Mauris vitae eleifend diam. Proin vel leo sit amet orci suscipit tincidunt. Mauris hendrerit, risus nec pharetra finibus, nulla eros sodales purus, nec semper eros nunc non lectus. Nullam facilisis libero at nisi ornare luctus. Maecenas consequat et nunc ut maximus. Sed quis est turpis. Fusce id dolor nec tortor varius sagittis scelerisque eget odio.
        Morbi facilisis sed ante ac fringilla. Donec eleifend, justo ut volutpat semper, tortor urna faucibus ipsum, sed egestas arcu mauris ac leo. Quisque facilisis enim et neque pulvinar, sit amet lacinia elit sagittis. In cursus nisl ac aliquam tempus. Aliquam eros sapien, porta porta dictum nec, iaculis vitae leo. Donec at aliquam elit. Phasellus tincidunt non nunc vitae vehicula. Sed eget augue enim.
        Pellentesque ut diam nec nisi molestie dignissim. Donec placerat scelerisque nunc nec fringilla. Pellentesque eleifend purus neque, quis volutpat tellus lacinia sed. Interdum et malesuada fames ac ante ipsum primis in faucibus. Pellentesque bibendum justo nec tortor euismod, in congue mauris pharetra. Etiam in est quam. Donec pretium non diam at lacinia. Nam vulputate ultricies libero, ac interdum lorem commodo eu. Quisque lectus lorem, faucibus id molestie in, interdum eu mauris. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Proin convallis, sapien tincidunt molestie feugiat, libero metus sodales augue, at vulputate lorem nulla quis dui. Aenean eu velit eros. Morbi a malesuada orci, nec cursus neque. In mattis eros eget gravida rutrum. In in dignissim lorem. Etiam a scelerisque magna, in venenatis magna.
        Integer eu est odio. Vivamus sollicitudin porta quam ut imperdiet. Duis dictum tempor accumsan. Fusce hendrerit elit augue, sit amet auctor quam malesuada et. Suspendisse dapibus finibus nunc. Quisque semper ullamcorper diam at sollicitudin. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Quisque et nunc mattis, ultrices risus vel, dignissim mi. Phasellus sodales ut erat nec efficitur. Nulla dolor tortor, tristique at aliquet eu, facilisis vitae tellus. Quisque sed metus sit amet nisi dignissim elementum ac eu eros. Aenean eu neque a ante faucibus ultrices. Nullam ut nisi pharetra, lobortis leo eu, ultricies ligula. Morbi enim risus, facilisis at tempus in, pulvinar at lacus. Suspendisse tempus facilisis pharetra. Nullam vel dictum est, vel bibendum mauris.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean maximus nunc elit, a consectetur mauris venenatis sed. Sed condimentum risus nec libero pretium viverra non ut lectus. Etiam in dui vitae leo lacinia tincidunt. Sed interdum, elit non porta condimentum, justo tellus pharetra massa, et consectetur nibh odio quis orci. Donec ac tristique velit, a congue lorem. Nulla at aliquet metus, id aliquam arcu. Integer aliquet, neque eu vehicula condimentum, nisi augue vulputate purus, ut pretium ex ex et turpis. Cras varius sapien eu augue commodo dignissim. Vestibulum ac sapien ligula. Quisque condimentum diam nec sapien mattis ultrices in pellentesque ex. Phasellus sit amet ornare ipsum. Pellentesque ultrices tincidunt felis. Nunc consectetur pellentesque augue, sed tincidunt turpis efficitur eget.
        Duis tempor sodales tellus, eget elementum ante volutpat nec. Aliquam eget eleifend neque, at lacinia nulla. Maecenas volutpat ex et mollis tincidunt. Etiam interdum dui nec fermentum facilisis. Ut auctor nulla turpis, sed ultricies quam tempor ac. Duis et risus quis eros pretium porta. Aenean in dolor id nisi aliquet vestibulum. Vestibulum quam ipsum, semper a metus vel, consequat egestas ipsum. Sed lorem odio, dictum ut viverra sit amet, fringilla non tellus. Mauris vitae eleifend diam. Proin vel leo sit amet orci suscipit tincidunt. Mauris hendrerit, risus nec pharetra finibus, nulla eros sodales purus, nec semper eros nunc non lectus. Nullam facilisis libero at nisi ornare luctus. Maecenas consequat et nunc ut maximus. Sed quis est turpis. Fusce id dolor nec tortor varius sagittis scelerisque eget odio.
        Morbi facilisis sed ante ac fringilla. Donec eleifend, justo ut volutpat semper, tortor urna faucibus ipsum, sed egestas arcu mauris ac leo. Quisque facilisis enim et neque pulvinar, sit amet lacinia elit sagittis. In cursus nisl ac aliquam tempus. Aliquam eros sapien, porta porta dictum nec, iaculis vitae leo. Donec at aliquam elit. Phasellus tincidunt non nunc vitae vehicula. Sed eget augue enim.
        DashboardLorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean maximus nunc elit, a consectetur mauris venenatis sed. Sed condimentum risus nec libero pretium viverra non ut lectus. Etiam in dui vitae leo lacinia tincidunt. Sed interdum, elit non porta condimentum, justo tellus pharetra massa, et consectetur nibh odio quis orci. Donec ac tristique velit, a congue lorem. Nulla at aliquet metus, id aliquam arcu. Integer aliquet, neque eu vehicula condimentum, nisi augue vulputate purus, ut pretium ex ex et turpis. Cras varius sapien eu augue commodo dignissim. Vestibulum ac sapien ligula. Quisque condimentum diam nec sapien mattis ultrices in pellentesque ex. Phasellus sit amet ornare ipsum. Pellentesque ultrices tincidunt felis. Nunc consectetur pellentesque augue, sed tincidunt turpis efficitur eget.
        Duis tempor sodales tellus, eget elementum ante volutpat nec. Aliquam eget eleifend neque, at lacinia nulla. Maecenas volutpat ex et mollis tincidunt. Etiam interdum dui nec fermentum facilisis. Ut auctor nulla turpis, sed ultricies quam tempor ac. Duis et risus quis eros pretium porta. Aenean in dolor id nisi aliquet vestibulum. Vestibulum quam ipsum, semper a metus vel, consequat egestas ipsum. Sed lorem odio, dictum ut viverra sit amet, fringilla non tellus. Mauris vitae eleifend diam. Proin vel leo sit amet orci suscipit tincidunt. Mauris hendrerit, risus nec pharetra finibus, nulla eros sodales purus, nec semper eros nunc non lectus. Nullam facilisis libero at nisi ornare luctus. Maecenas consequat et nunc ut maximus. Sed quis est turpis. Fusce id dolor nec tortor varius sagittis scelerisque eget odio.
        Morbi facilisis sed ante ac fringilla. Donec eleifend, justo ut volutpat semper, tortor urna faucibus ipsum, sed egestas arcu mauris ac leo. Quisque facilisis enim et neque pulvinar, sit amet lacinia elit sagittis. In cursus nisl ac aliquam tempus. Aliquam eros sapien, porta porta dictum nec, iaculis vitae leo. Donec at aliquam elit. Phasellus tincidunt non nunc vitae vehicula. Sed eget augue enim.
        Pellentesque ut diam nec nisi molestie dignissim. Donec placerat scelerisque nunc nec fringilla. Pellentesque eleifend purus neque, quis volutpat tellus lacinia sed. Interdum et malesuada fames ac ante ipsum primis in faucibus. Pellentesque bibendum justo nec tortor euismod, in congue mauris pharetra. Etiam in est quam. Donec pretium non diam at lacinia. Nam vulputate ultricies libero, ac interdum lorem commodo eu. Quisque lectus lorem, faucibus id molestie in, interdum eu mauris. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Proin convallis, sapien tincidunt molestie feugiat, libero metus sodales augue, at vulputate lorem nulla quis dui. Aenean eu velit eros. Morbi a malesuada orci, nec cursus neque. In mattis eros eget gravida rutrum. In in dignissim lorem. Etiam a scelerisque magna, in venenatis magna.
        Integer eu est odio. Vivamus sollicitudin porta quam ut imperdiet. Duis dictum tempor accumsan. Fusce hendrerit elit augue, sit amet auctor quam malesuada et. Suspendisse dapibus finibus nunc. Quisque semper ullamcorper diam at sollicitudin. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Quisque et nunc mattis, ultrices risus vel, dignissim mi. Phasellus sodales ut erat nec efficitur. Nulla dolor tortor, tristique at aliquet eu, facilisis vitae tellus. Quisque sed metus sit amet nisi dignissim elementum ac eu eros. Aenean eu neque a ante faucibus ultrices. Nullam ut nisi pharetra, lobortis leo eu, ultricies ligula. Morbi enim risus, facilisis at tempus in, pulvinar at lacus. Suspendisse tempus facilisis pharetra. Nullam vel dictum est, vel bibendum mauris.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean maximus nunc elit, a consectetur mauris venenatis sed. Sed condimentum risus nec libero pretium viverra non ut lectus. Etiam in dui vitae leo lacinia tincidunt. Sed interdum, elit non porta condimentum, justo tellus pharetra massa, et consectetur nibh odio quis orci. Donec ac tristique velit, a congue lorem. Nulla at aliquet metus, id aliquam arcu. Integer aliquet, neque eu vehicula condimentum, nisi augue vulputate purus, ut pretium ex ex et turpis. Cras varius sapien eu augue commodo dignissim. Vestibulum ac sapien ligula. Quisque condimentum diam nec sapien mattis ultrices in pellentesque ex. Phasellus sit amet ornare ipsum. Pellentesque ultrices tincidunt felis. Nunc consectetur pellentesque augue, sed tincidunt turpis efficitur eget.
        Duis tempor sodales tellus, eget elementum ante volutpat nec. Aliquam eget eleifend neque, at lacinia nulla. Maecenas volutpat ex et mollis tincidunt. Etiam interdum dui nec fermentum facilisis. Ut auctor nulla turpis, sed ultricies quam tempor ac. Duis et risus quis eros pretium porta. Aenean in dolor id nisi aliquet vestibulum. Vestibulum quam ipsum, semper a metus vel, consequat egestas ipsum. Sed lorem odio, dictum ut viverra sit amet, fringilla non tellus. Mauris vitae eleifend diam. Proin vel leo sit amet orci suscipit tincidunt. Mauris hendrerit, risus nec pharetra finibus, nulla eros sodales purus, nec semper eros nunc non lectus. Nullam facilisis libero at nisi ornare luctus. Maecenas consequat et nunc ut maximus. Sed quis est turpis. Fusce id dolor nec tortor varius sagittis scelerisque eget odio.
        Morbi facilisis sed ante ac fringilla. Donec eleifend, justo ut volutpat semper, tortor urna faucibus ipsum, sed egestas arcu mauris ac leo. Quisque facilisis enim et neque pulvinar, sit amet lacinia elit sagittis. In cursus nisl ac aliquam tempus. Aliquam eros sapien, porta porta dictum nec, iaculis vitae leo. Donec at aliquam elit. Phasellus tincidunt non nunc vitae vehicula. Sed eget augue enim.
        Pellentesque ut diam nec nisi molestie dignissim. Donec placerat scelerisque nunc nec fringilla. Pellentesque eleifend purus neque, quis volutpat tellus lacinia sed. Interdum et malesuada fames ac ante ipsum primis in faucibus. Pellentesque bibendum justo nec tortor euismod, in congue mauris pharetra. Etiam in est quam. Donec pretium non diam at lacinia. Nam vulputate ultricies libero, ac interdum lorem commodo eu. Quisque lectus lorem, faucibus id molestie in, interdum eu mauris. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Proin convallis, sapien tincidunt molestie feugiat, libero metus sodales augue, at vulputate lorem nulla quis dui. Aenean eu velit eros. Morbi a malesuada orci, nec cursus neque. In mattis eros eget gravida rutrum. In in dignissim lorem. Etiam a scelerisque magna, in venenatis magna.
        Integer eu est odio. Vivamus sollicitudin porta quam ut imperdiet. Duis dictum tempor accumsan. Fusce hendrerit elit augue, sit amet auctor quam malesuada et. Suspendisse dapibus finibus nunc. Quisque semper ullamcorper diam at sollicitudin. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Quisque et nunc mattis, ultrices risus vel, dignissim mi. Phasellus sodales ut erat nec efficitur. Nulla dolor tortor, tristique at aliquet eu, facilisis vitae tellus. Quisque sed metus sit amet nisi dignissim elementum ac eu eros. Aenean eu neque a ante faucibus ultrices. Nullam ut nisi pharetra, lobortis leo eu, ultricies ligula. Morbi enim risus, facilisis at tempus in, pulvinar at lacus. Suspendisse tempus facilisis pharetra. Nullam vel dictum est, vel bibendum mauris.
      </LayoutShell>
    );
  }
});

export default DashboardPage;
